name: Generate Documentation

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
            java-version: 8
            distribution: jdk
            architecture: x64
            check-latest: false
            server-id: github
            server-username: GITHUB_ACTOR
            server-password: GITHUB_TOKEN
            overwrite-settings: true
            job-status: success

      - name: Build and Generate Documentation
        run: |
          ./gradlew build
          ./gradlew dokkaHtml
